// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydmgkanfqjqdpszncckc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbWdrYW5mcWpxZHBzem5jY2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDU5NjAsImV4cCI6MjA2NzI4MTk2MH0.8hJHNwXNzIzAYC-BYafciTlLc_CPzpkXvqJ0ER-uj8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});